// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI;

#nullable disable

namespace Cahtbot.Migrations
{
    [DbContext(typeof(ChatbotContext))]
    partial class ChatbotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cahtbot.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataDigest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_digest");

                    b.Property<string>("FromCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_code");

                    b.Property<string>("LogisticsInterface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logistics_interface");

                    b.Property<string>("MsgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("msg_id");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("msg_type");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("partner_code");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
